[package]
name = "arcanum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = { version = "0.9", features = ["armor", "ssh"] }
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
env_logger = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toor = "0.2"
tracing = "0.1"
tracing-subscriber = "0.3"
whoami = "1.4"
